### ISSUE TITLE
AUR

### ISSUE THREAD

**Issue by ishanarora** [Zile995/booster-um#14]
Hi! Thanks for your project. Would you consider submitting it to AUR please?

**Comment by Zile995** [comment]
Hi!

If you think the script is of good quality and people would use it, I can definitely submit it.  :slightly_smiling_face:

**Comment by Zile995** [comment]
As requested, the packages have been submitted to the AUR.

[booster-um](https://aur.archlinux.org/packages/booster-um-git) and [booster-um-git](https://aur.archlinux.org/packages/booster-um-git)
